# site.yml
---

- hosts: build
  become: true
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
  tasks:
    - name: copy SSH config file to VM
      copy:
        src: files/config
        dest: /home/vagrant/.ssh/
    - name: Portforward port 80 to 8080 with iptables
      shell: iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 172.16.128.10:8080

- hosts: app
  become: true
  tasks:
    - name: copy SSH config file to VM
      copy:
        src: files/config
        dest: /home/vagrant/.ssh/
    - name: Make project directory
      file: 
        path: /home/vagrant/project
        state: directory
        owner: vagrant
        group: vagrant
    - name: Copy docker-compose file to project directory
      copy:
        src: files/docker-compose.yml
        dest: /home/vagrant/project/